### ISSUE TITLE
OLED does not work at Volumio 2.882 at RaspDac Mini OLED

### ISSUE THREAD

**Issue by McDin** [audiophonics/RaspDacMini#1]
After updating to new Volumio the OLED works for few minutes. After that the letters are inverted and the clock is split.

Now I tried to use your install.sh but the screen does not turn on after reboot.

Are you working on a solution or is there a fix yet?

Thanks :)

**Comment by audiophonics** [comment]
There are multiple different issues here. 
The install script will not work on Volumio versions 2.878 and 2.882 because those versions lacks the tools to compile software. There is a workaround that can be found here : [https://community.volumio.org/t/cannot-install-build-essential-package/46856/16](https://community.volumio.org/t/cannot-install-build-essential-package/46856/16). The procedure described there will allow the install.sh to do its job. Otherwise the same result can be achieved by using our custom image and doing a regular system update through the Volumio interface.


However, rebuilding the oled driver on an updated Volumio will not fix the inverted display. This is a separate issue that we are aware of and (as we know) is specific to RaspDac Mini Oled version using a Raspberry Pi 3B+. It boils down to a somewhat outdated spi interface that on certain rare occasions will misfires its callback before the buffer frame is complete.  
I am still trying to figure out a way to fix this, but this is a really low level issue and most of what I have achieved so far was to make the bug happen later in time. 

Considering how painful it has become to maintain a Python framework that is working, reliable and up-to-date on Volumio, I am working on a new SPI oled interface using exclusively nodejs. That will hopefully fix the reverted display issue on the Mini Oled 3B+ as well as some spikes of memory consumption that can happen with this framework (regardless of the version or model, mini oled 3b+ / 4 & Evo). It will also drastically decrease the installation time since most binaries are already available in both Volumio and moOde. 


Meanwhile, here are some dirty fixes that can help coping with any issues experienced with the Mini Oled Display or the Evo secondary display :

- You can restart the display without rebooting the Pi. Evo and RaspDacMini have a small web interface on port 4150 that allow you to restart the display instantly  Go to http://volumio:4150 and click the "Restart OLED" button. 
- Since the OLED driver is loaded as a service, it is also possible to `sudo systemctl restart oled` from ssh or even to edit the service configuration file ( ` sudo nano /etc/systemd/system/oled.service` ) for periodic self-restart (I have found a restart every 10 minutes to be somewhat acceptable on a fresh 3B+). 
-  If the logo is bothering you on OLED restart, you can remove it by editing RaspDacMini/volumio/oled/oled.py as follow : ` #page_manager.display_page("logo_page")`  line 58 -> commenting    
`time.sleep(0.5)` line 59 -> change value from 6 to 0.5
-  If everything fails, another solution would be to downgrade to a [previous image](https://mega.nz/file/AFhQ3Yqa#owxBPT3ZhEH0fPHDOOFRGeyl7NT6766tzGbS8cm3nh4 ) which uses an older OLED driver with a slower refresh rate.

Please remember that the fixes described above are nothing but workarounds to help pi3 users live with the bug while a new framework is being built. Those are not definitive solutions.

**Comment by audiophonics** [comment]
I have updated the whole OLED process with a new script now using nodejs. 
You can find a pre-built Volumio image (2.882) with this new version [here](https://mega.nz/file/ccRSBBJD#3MHNxv_FW6h9HdvP2p0cy8hK4jPF2rvHmH4ePO9581Y). 
I have tested it on several scenarios (and still am) but there might be small graphical bugs that I failed to see, so let me know if anything weird happen.

**Comment by McDin** [comment]
Thank you very much. I will give it a try :)

**Comment by McDin** [comment]
Hi,
I have tested this versions for two weeks now. The screen bug is fixed, but there is a new problem. The DAC does not start some times so I have to flash it new. With my "old version" where I updated through Volumio and the old display drivers I don't have this problem.
Can you please fix it?

**Comment by audiophonics** [comment]
> Hi,
> I have tested this versions for two weeks now. The screen bug is fixed, but there is a new problem. The DAC does not start some times so I have to flash it new. With my "old version" where I updated through Volumio and the old display drivers I don't have this problem.
> Can you please fix it?

I'll have a look asap.

**Comment by McDin** [comment]
Hi, can you support this thread??? I have to flash and flash it...

**Comment by audiophonics** [comment]
Hi,

Until now I have not been able to reproduce this behavior. 
I have an update that is coming soon. It might fix that bug but honestly it sounds that a firmware mismatch or something wrong with the SD card. If the next update does not solve the issue, I suggest contact directly Audiophonics support since they are way more knowledgable than me when it comes to specific / hardware bugs.

**Comment by McDin** [comment]
Okay, I will try it. I already tested stock Volumio and the error does not occur. Same as with the older version. It is only this combination that makes the problem
