### ISSUE TITLE
for Raspdac 9023 dac display connected as minikit 

### ISSUE THREAD

**Issue by RP250258** [audiophonics/RaspDacMini#4]
Dear Audiophonics, can I use this with the Raspdac 9023, with the display connected as the Minikit?

**Comment by audiophonics** [comment]
The oled script provided here is not designed to handle the original Winstar WEH001602A display found in the Raspdac 9023 version but if you changed this display to a ssd1306 controlled one, the OLED script should work fine. 

Other components, such as remote & dac options need the es90x8 DAC to actually respond in order to work so those will never be usable here without heavy code modification. 

I would suggest that using this current repository on a 9023 is overall a bad idea. You need something [like this](https://github.com/JedS/Raspdac) in order to make your display work. It uses a old plugin install procedure but the base code is a good example of how to achieve this.
